### ISSUE TITLE
How to register a new channel ???//چطور میشه کانال جدید ایجاد کرد ؟؟؟

### ISSUE THREAD

**Issue by jepbura** [chabok-io/chabok-client-flutter#2]
سلام
چطور میتونم در فلاتر برای هر کاربر کانال خصوصی ایجاد کنم ؟؟؟

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام
<br>
بخش مربوط به <a href="https://doc.chabok.io/flutter/chabok-messaging.html">ارسال پیام</a> رو مطالعه کنید و همینطور قطعه کد مربوط به ارسال پیام روی یک کانال در <a href="https://github.com/chabok-io/chabok-client-flutter/blob/master/android/src/main/java/com/chabokpush/flutter/chabokpush/ChabokpushPlugin.java#L296">نمونه کد برنامه کلاینت فلاتر</a> رو تست کنید
<br>
اگر مشکلی بود در خدمتم
</div>

**Comment by jepbura** [comment]
درسته منم همون قسمت راهنما ها رو قبلش خوندم 

طبق این کدی که شما در [ارسال پیام](https://doc.chabok.io/flutter/chabok-messaging.html#%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D9%BE%DB%8C%D8%A7%D9%85) گذاشتید 
> ChabokPush.shared.publish(new ChabokMessage("User_Id", "channel","message"));

ظاهرا میاد پیام رو به کاربری میده که در کانال خصوصی مربوطه قبلا ثبت نام کرده باشه ، درسته ؟؟؟

شما در قسمت آموزش [عضویت روی کانال](https://doc.chabok.io/android/chabok-messaging.html#%DA%A9%D8%A7%D9%86%D8%A7%D9%84) ، مربوط به اندروید (جاوا) کدی رو قرار دادید که در اون برای عضویت در کانال از متد
 `subscribe ` 
استفاده شده. 
من این متدرو میخواستم خودم دستی اضافه کنم اما اونو تو کتابخونه های چابک پیدا نکردم ، میشه بگید تو کدوم کتابخونه هستش ؟؟؟
اگه نیستش ممکنه کدش رو بگید اضافه کنم .

> //Subscribe on public alert channel.
AdpPushClient.get().subscribe("alert", new Callback() {...});

> //Subscribe on private league channel.
AdpPushClient.get().subscribe("private/league", new Callback() {...});

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام
<br>
بابت تاخیر در پاسخگویی عذرخواهی میکنم
<br>
برای <a href="https://doc.chabok.io/flutter/chabok-messaging.html#%D8%AF%D8%B1%DB%8C%D8%A7%D9%81%D8%AA-%D9%BE%DB%8C%D8%A7%D9%85">دریافت پیام</a> از متد setOnMessageCallback استفاده کنید
<br>
ثبتنام روی کانال default خودکار انجام میشه ولی اگر به کانال دیگری نیاز دارید و درکدهای dart به متد subscribe دسترسی ندارید عضویت روی کانال را از طریق کدهای native هر پلتفرم جداگانه انجام دهید.
</div>
