### ISSUE TITLE
Support for ios devices.

### ISSUE THREAD

**Issue by erfanhemmati** [chabok-io/chabok-client-flutter#3]
does this package support for ios devices ?
@farbod-s 
@Husseinhj @chabok-io

**Comment by farbod-s** [comment]
Hi @erfanhemmati 
The new version of Chabok SDK for flutter that supports the iOS platform, will be released this week. we will notify you about it.

**Comment by erfanhemmati** [comment]
@farbod-s 
Really getting ready this week? Thank you very much

**Comment by Husseinhj** [comment]
@erfanhemmati 
> Really getting ready this week? Thank you very much

It's available on version 1.0.+.

**Comment by erfanhemmati** [comment]
@farbod-s @chabok-io @Husseinhj 
Thank you very much :) :) 👍
